### ISSUE TITLE
BUG: 100% chance to double the dish

### ISSUE THREAD

**Issue by godluck** [Pet-Slime/StardewValley#22]
https://github.com/Pet-Slime/StardewValley/blob/505d0bbeda33a0a4ef1afcc81312668c4a3c84aa/CookingSkillRedux/Core/Utilities.cs#L22

Does this mean the chance to double the dish is ((lv)*0.03+1) * 2? It's 260% for lv 10

**Comment by Pet-Slime** [comment]
Fixed in 1.7.0, thank you for pointing that out.
