### ISSUE TITLE
Yellow Spam in SMAPI Console

### ISSUE THREAD

**Issue by jameshart197** [Pet-Slime/StardewValley#29]
Not sure if its an issue/bug, or just required for the skill, but SMAPI seems to check for my Luck Skill very very frequently, resulting in multiple messages saying [LuckSkill] Luck: Player luck level is: X
Attached a screenshot. No log provided right now because its coming up as too large for smapi.io/log (I've had stardew open a long long time). 
I will provide one when possible. 
![Luckskill](https://github.com/Pet-Slime/StardewValley/assets/114915139/c2585e5d-6f54-4d1a-b727-65fed92e1074)

**Comment by telcrazy** [comment]
I also encountered this problem, have you solved it?

**Comment by DeLiXx** [comment]
Hello, I'd appreciate it if you could not print so many warnings, it's quite disruptive.
A good alternative solution would be to add a config for DebugLogs, which will toggle all your prints from Trace to Debug

**Comment by Pet-Slime** [comment]
i"ll update the mod with in the month to change the logging. Everything seems to be functional (no one has reported any bugs, just the log spam) so it's no longer really necessary.
